# Generated by Django 3.2.8 on 2022-02-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(default=12)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('PRE-IELTS', 'Pre-ielts'), ('IELTS', 'Ielts'), ('FOUNDATION', 'Foundation'), ('GRADUATION', 'Graduation')], default='BEGINNER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ielts_level', models.CharField(choices=[('+6.5 score', '+6.5 score'), ('+7.0 score', '+7.0 score'), ('+7.5 score', '+7.5 score'), ('+8.0 score', '+8.0 score'), ('+8.5 score', '+8.5 score'), ('+9.0 score', '+9.0 score')], default='+7.0 score', max_length=20)),
                ('age', models.PositiveSmallIntegerField(default=16)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking'), ('FULL', 'Full')], default='FULL', max_length=20)),
                ('read_num', models.PositiveIntegerField()),
                ('students', models.ManyToManyField(related_name='students', to='books.Students')),
                ('teachers', models.ManyToManyField(related_name='teachers', to='books.Teachers')),
            ],
        ),
    ]
